#
# Ubuntu Node.js Dockerfile
#
# https://github.com/dockerfile/ubuntu/blob/master/Dockerfile
# https://docs.docker.com/examples/nodejs_web_app/
#

# Pull base image.
FROM ubuntu

RUN apt-get update -yq && apt-get upgrade -yq 
RUN apt-get install -yq curl git nano sudo

# install from nodesource using apt-get
# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server
RUN curl -sL https://deb.nodesource.com/setup |sudo bash - 
RUN apt-get install -yq nodejs build-essential

# fix npm - not the latest version installed by apt-get


# Install Node.js
#RUN apt-get install --yes curl
#RUN curl --silent --location https://deb.nodesource.com/setup_6.x | sudo bash -
#RUN apt-get install --yes nodejs
#RUN apt-get install --yes build-essential

WORKDIR /app

# Bundle app source
# Trouble with COPY http://stackoverflow.com/a/30405787/2926832
COPY . /app

# Install app dependencies
RUN cd /app

RUN npm install


RUN npm install -g mockserver
# Binds to port 8080
EXPOSE  9000

CMD ["tail -f /dev/null"]
# These commands unlike RUN (they are carried out in the construction of the container) are run when the container
#ENTRYPOINT ["/usr/local/bin/mockserver -p 9000 -m mocks "]
